version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Squ!dnug!1
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/web-dev-api
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: