### GET request to example server
GET http://127.0.0.1:8000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
###
POST 127.0.0.1:8000/users/
Content-Type: application/json

{
  "email": "happy@gmail.com",
  "password": "happypass",
  "account_type": "admin"
}
###
GET 127.0.0.1:8000/users/johndoe@gmail.com/
###
DELETE 127.0.0.1:8000/users/1/
###

GET http://127.0.0.1:8000/schools/
###

POST 127.0.0.1:8000/schools/
Content-Type: application/json

{
  "name": "School of Rock",
  "address": "New York/New York/USA",
  "city": "New York",
  "county": "New York",
  "postcode": "10001",
  "phone": 1234567890,
  "website": "www.schoolofrock.com",
  "domain": "schoolofrock.com"
}

###
GET 127.0.0.1:8000/sessions/
###
GET 127.0.0.1:8000/sessions/supervisor/1
###
GET 127.0.0.1:8000/sessions/client/1
###
GET 127.0.0.1:8000/sessions/school/1
###
GET 127.0.0.1:8000/session_edits/
###
POST 127.0.0.1:8000/sessions/
Content-Type: application/json

{
  "school_id": null,
  "supervisor_id": 3,
  "supervisor_email": "henrymcconville@example.com",
  "client_id": 7,
  "client_email": "henrymcconville@gmail.com",
  "date": "2021-01-01",
  "additional_info": "This is a test session"
}

###
DELETE 127.0.0.1:8000/users/henrymcconville@testschool.com
###
GET 127.0.0.1:8000/contact/
###
POST 127.0.0.1:8000/session_edits/
Content-Type: application/json

{
  "session_id": 2,
  "school_id": null,
  "supervisor_id": 3,
  "supervisor_email": "henrymcconville@example.com",
  "client_id": 5,
  "client_email": "henrymcconville@testschool.com",
  "date": "2025-03-14",
  "request": "This is a test request",
  "additional_info": "This is a test additional info"
}
###
DELETE 127.0.0.1:8000/session_edits/1
###
GET 127.0.0.1:8000/token
Authorization: Bearer "token"