### GET request to example server
GET http://127.0.0.1:8000/users/
###
POST 127.0.0.1:8000/users/
Content-Type: application/json

{
  "email": "johndoe@gmail.com",
  "password": "johnpass"
}
###
GET 127.0.0.1:8000/users/johndoe@gmail.com/
###
DELETE 127.0.0.1:8000/users/1/